// Code generated by counterfeiter. DO NOT EDIT.
package fake

import (
	"io"
	"sync"

	"github.com/st3v/plotq/converter"
)

type Convert struct {
	Stub        func(io.Reader, ...converter.Option) io.WriterTo
	mutex       sync.RWMutex
	argsForCall []struct {
		arg1 io.Reader
		arg2 []converter.Option
	}
	returns struct {
		result1 io.WriterTo
	}
	returnsOnCall map[int]struct {
		result1 io.WriterTo
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *Convert) Spy(arg1 io.Reader, arg2 ...converter.Option) io.WriterTo {
	fake.mutex.Lock()
	ret, specificReturn := fake.returnsOnCall[len(fake.argsForCall)]
	fake.argsForCall = append(fake.argsForCall, struct {
		arg1 io.Reader
		arg2 []converter.Option
	}{arg1, arg2})
	stub := fake.Stub
	returns := fake.returns
	fake.recordInvocation("Convert", []interface{}{arg1, arg2})
	fake.mutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2...)
	}
	if specificReturn {
		return ret.result1
	}
	return returns.result1
}

func (fake *Convert) CallCount() int {
	fake.mutex.RLock()
	defer fake.mutex.RUnlock()
	return len(fake.argsForCall)
}

func (fake *Convert) Calls(stub func(io.Reader, ...converter.Option) io.WriterTo) {
	fake.mutex.Lock()
	defer fake.mutex.Unlock()
	fake.Stub = stub
}

func (fake *Convert) ArgsForCall(i int) (io.Reader, []converter.Option) {
	fake.mutex.RLock()
	defer fake.mutex.RUnlock()
	return fake.argsForCall[i].arg1, fake.argsForCall[i].arg2
}

func (fake *Convert) Returns(result1 io.WriterTo) {
	fake.mutex.Lock()
	defer fake.mutex.Unlock()
	fake.Stub = nil
	fake.returns = struct {
		result1 io.WriterTo
	}{result1}
}

func (fake *Convert) ReturnsOnCall(i int, result1 io.WriterTo) {
	fake.mutex.Lock()
	defer fake.mutex.Unlock()
	fake.Stub = nil
	if fake.returnsOnCall == nil {
		fake.returnsOnCall = make(map[int]struct {
			result1 io.WriterTo
		})
	}
	fake.returnsOnCall[i] = struct {
		result1 io.WriterTo
	}{result1}
}

func (fake *Convert) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.mutex.RLock()
	defer fake.mutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *Convert) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ converter.Convert = new(Convert).Spy
